'use client';
import {useEffect,useRef,useState} from 'react';
import {Plus,Check,ArrowRight,RefreshCw,Sparkles,Copy,PackageCheck,ExternalLink} from 'lucide-react';
import {Frame} from '../customer';
import {api,read,ZONES,money,time} from '../shared';
type Row=Record<string,any>;
export default function Merchant(){
 const [data,setData]=useState<Row|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('requests'),[auto,setAuto]=useState(false),[aiNote,setAiNote]=useState(''),[ranks,setRanks]=useState<Record<string,string[]>>({}),[codes,setCodes]=useState<Record<string,string>>({}),[form,setForm]=useState(false),[notice,setNotice]=useState('');
 const worker=useRef<Worker|null>(null),pending=useRef(new Map<string,{resolve:(v:any)=>void,reject:(e:any)=>void}>()),loop=useRef(false),autoRef=useRef(false),seen=useRef(new Set<string>());
 const [venue,setVenue]=useState({name:'',address:'',phone:'',zone:ZONES[0],demo:true,authorized:false});const [meal,setMeal]=useState({name:'',description:'',price:'8',stock:5,prep:10,vegetarian:false});
 async function refresh(){try{const d=await read('view=merchant');setData(d);return d}catch(e:any){setError(e.message);return null}}
 useEffect(()=>{refresh();const t=setInterval(refresh,7000);return()=>{clearInterval(t);worker.current?.terminate();for(const p of pending.current.values())p.reject(new Error('Pannello chiuso'))}},[]);
 useEffect(()=>{autoRef.current=auto},[auto]);
 const eligible=(r:Row,menu:Row[])=>menu.filter(m=>m.available>=r.quantity&&m.price*r.quantity<=r.budget&&(!r.vegetarian||m.vegetarian)&&Date.now()+(m.prep+3)*60000<r.pickup_by&&m.updated>Date.now()-86400000);
 function rank(r:Row,items:Row[]):Promise<any>{return new Promise((resolve,reject)=>{
  if(!worker.current){worker.current=new Worker('/lunch-ranker.worker.js',{type:'module'});worker.current.onmessage=({data:e})=>{if(e.type==='progress'){setAiNote(e.stage==='download'?`Primo avvio: scaricamento modello ${e.progress?Math.round(e.progress)+'%':''}`:e.stage==='inference'?'L’AI confronta richiesta e piatti…':'Avvio AI locale…')}if(e.type==='result'){setAiNote(`Confronto AI eseguito sul dispositivo in ${e.timings.inferenceMs} ms.`);pending.current.get(e.id)?.resolve(e);pending.current.delete(e.id)}if(e.type==='error'){setAiNote(e.message);pending.current.get(e.id)?.reject(new Error(e.message));pending.current.delete(e.id)}};worker.current.onerror=()=>{setAiNote('AI non disponibile. Puoi rispondere manualmente.');setAuto(false);for(const p of pending.current.values())p.reject(new Error('AI non disponibile.'));pending.current.clear()}}
  const id=crypto.randomUUID();pending.current.set(id,{resolve,reject});worker.current.postMessage({id,query:r.wish||'Una proposta per il pranzo',items:items.map(m=>({id:m.id,name:m.name,description:m.description}))});
 })}
 async function suggest(r:Row){const items=eligible(r,data?.menu||[]);if(!items.length)return;setBusy(true);setError('');try{const result=await rank(r,items);setRanks(old=>({...old,[r.id]:result.order}))}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 useEffect(()=>{if(!auto||!data||loop.current)return;const r=data.requests.find((r:Row)=>!seen.current.has(r.id)&&!data.offers.some((o:Row)=>o.request_id===r.id)&&eligible(r,data.menu).length);if(!r)return;loop.current=true;seen.current.add(r.id);(async()=>{try{const result=await rank(r,eligible(r,data.menu));if(!autoRef.current)return;await api('offer',{requestId:r.id,menuId:result.order[0]});setNotice('L’AI ha inviato una proposta dal tuo menù, entro budget e tempi.');await refresh()}catch(e:any){setError(e.message);setAuto(false)}finally{loop.current=false}})()},[data,auto]);
 async function run(action:string,payload:Row={}){setBusy(true);setError('');try{const d=await api(action,payload);await refresh();return d}catch(e:any){setError(e.message);return null}finally{setBusy(false)}}
 async function createVenue(e:React.FormEvent){e.preventDefault();await run('venue',venue)}
 async function trial(){setBusy(true);setError('');try{await api('venue',{name:'Banco prova Food Arena',address:'Punto dimostrativo: nessun ritiro reale',phone:'',zone:ZONES[0],demo:true,authorized:true});for(const m of [{name:'Pasta al pomodoro + acqua',description:'Pasta calda al pomodoro, acqua 500 ml. Confezione inclusa. Dati dimostrativi.',price:850,stock:6,prep:8,vegetarian:true},{name:'Piadina verdure + acqua',description:'Piadina con verdure grigliate e formaggio, acqua 500 ml. Confezione inclusa. Dati dimostrativi.',price:950,stock:4,prep:5,vegetarian:true},{name:'Panino pollo + acqua',description:'Panino con pollo e insalata, acqua 500 ml. Confezione inclusa. Dati dimostrativi.',price:1000,stock:5,prep:7,vegetarian:false}])await api('menu',m);await refresh()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function addMeal(e:React.FormEvent){e.preventDefault();if(await run('menu',{...meal,price:Math.round(Number(meal.price)*100)})){setForm(false);setMeal({name:'',description:'',price:'8',stock:5,prep:10,vegetarian:false})}}
 async function chain(o:Row){setBusy(true);setError('');try{const p=await api('attest',{offerId:o.id});setNotice(p.confirmed?'Impronta confermata su Avalanche Fuji. Firma del portafoglio di prova Food Arena.':'Impronta inviata a Fuji. Apri la transazione per controllare la conferma.');await refresh()}catch(e:any){setError(e.message)}finally{setBusy(false)}}

 const n=Date.now(),v=data?.venue,offers=data?.offers||[],open=(data?.requests||[]).filter((r:Row)=>!offers.some((o:Row)=>o.request_id===r.id));
 return <Frame><main>{error&&<div className="error" role="alert">{error}</div>}{notice&&<div className="success" role="status">{notice}</div>}{!data?<p className="loading">Carico il pannello…</p>:!v?<div className="narrow"><span className="eyebrow">CREA IL TUO PUNTO DI RITIRO</span><h1 className="top-margin">Il tuo menù.<br/>La domanda vicino a te.</h1><div className="notice top-margin"><div><h3>Vuoi provarlo subito?</h3><p>Crea un banco di prova con tre piatti dimostrativi. Non vengono coinvolti locali reali.</p><button className="primary top-margin" disabled={busy} onClick={trial}>Attiva banco di prova <ArrowRight size={18}/></button></div></div><form className="request-card top-margin" onSubmit={createVenue}><h2>Oppure registra il tuo locale</h2><label className="top-margin">Nome del locale<input required value={venue.name} onChange={e=>setVenue({...venue,name:e.target.value})} maxLength={80}/></label><label>Indirizzo di ritiro<input required value={venue.address} onChange={e=>setVenue({...venue,address:e.target.value})} maxLength={180}/></label><div className="form-grid"><label>Zona<select value={venue.zone} onChange={e=>setVenue({...venue,zone:e.target.value})}>{ZONES.map(z=><option key={z}>{z}</option>)}</select></label><label>Telefono pubblico<input required={!venue.demo} type="tel" value={venue.phone} onChange={e=>setVenue({...venue,phone:e.target.value})}/></label></div><label className="checkline"><input type="checkbox" checked={venue.demo} onChange={e=>setVenue({...venue,demo:e.target.checked})}/> Locale di prova: nessun ordine reale.</label><label className="checkline"><input required type="checkbox" checked={venue.authorized} onChange={e=>setVenue({...venue,authorized:e.target.checked})}/> Sono autorizzato a gestire questo punto e i dati inseriti.</label><button className="primary wide" disabled={busy}>Crea il punto di ritiro</button></form></div>:<><div className="flex"><div><div className="eyebrow">{v.demo?'BANCO DI PROVA · NESSUN ORDINE REALE':'PANNELLO GESTORE'}</div><h1 style={{fontSize:'2.5rem',marginTop:12}}>{v.name}</h1><p className="help">{v.zone} · {v.address}</p></div><button className="secondary" onClick={refresh}><RefreshCw size={16}/> Aggiorna</button></div><div className="chips"><button className={tab==='requests'?'selected':''} onClick={()=>setTab('requests')}>Richieste ({open.length})</button><button className={tab==='offers'?'selected':''} onClick={()=>setTab('offers')}>Proposte e ritiri</button><button className={tab==='menu'?'selected':''} onClick={()=>setTab('menu')}>Menù e quantità</button></div>
 {tab==='requests'&&<><div className="ai-toggle"><label className="checkline"><input type="checkbox" checked={auto} onChange={e=>{setAuto(e.target.checked);autoRef.current=e.target.checked;if(!e.target.checked)setAiNote('Risposte automatiche fermate.')}}/> <Sparkles size={19}/> Rispondi automaticamente con l’AI</label><p>Autorizzi proposte solo dal tuo menù, per quantità disponibili ed entro budget e orario. Il pannello deve restare aperto. Per preferenze complesse usa la conferma manuale.</p><p>Primo avvio: circa 118 MB di modello. Poi l’AI lavora sul dispositivo.</p></div>{aiNote&&<p className="model-progress" role="status">{aiNote}</p>}{!open.length?<div className="empty"><h2>Nessuna nuova richiesta nella tua zona.</h2><p>Tieni aperto il pannello. Le richieste arrivano qui automaticamente.</p><a className="secondary top-margin" href="/" target="_blank">Apri il lato cliente per provare</a></div>:<div className="stack top-margin">{open.map((r:Row)=>{const candidates=eligible(r,data.menu),order=ranks[r.id],sorted=order?[...candidates].sort((a,b)=>order.indexOf(a.id)-order.indexOf(b.id)):candidates;return <article className="offer" key={r.id}><div className="flex"><h2>{money(r.budget)} totali · {r.quantity} {r.quantity===1?'persona':'persone'}</h2><span className="badge">Ritiro entro {time(r.pickup_by)}</span></div><p>{r.wish||'Aperto a proposte per pranzo.'}</p>{r.vegetarian===1&&<span className="pill">Vegetariano</span>}{!candidates.length?<p className="help">Nessun piatto rispetta quantità, budget e tempi. Puoi aggiungere una proposta al menù.</p>:<><div className="actions"><button className="secondary" disabled={busy} onClick={()=>suggest(r)}><Sparkles size={16}/>{order?'Aggiorna confronto AI':'Suggerisci con AI'}</button>{order&&<span className="caption">Piatti ordinati per affinità con la richiesta</span>}</div><div className="stack top-margin">{sorted.map((m:Row,i:number)=><div className="menu-choice" key={m.id}><div><strong>{r.quantity} × {m.name}</strong><p>{money(m.price*r.quantity)} totali · pronto entro {m.prep+3} min</p>{order&&i===0&&<small>Prima proposta secondo il modello · verifica le preferenze</small>}</div><button className="primary" disabled={busy} onClick={()=>run('offer',{requestId:r.id,menuId:m.id})}>Proponi <ArrowRight size={17}/></button></div>)}</div></>}</article>})}</div>}</>}
 {tab==='offers'&&<div className="stack">{!offers.length&&<div className="empty"><h2>Le tue proposte appariranno qui.</h2><p>Quando un cliente sceglie, ti mostriamo il ritiro da preparare.</p></div>}{offers.map((o:Row)=>{const expired=o.pickup_by<n||o.status==='offered'&&o.expires<n;return <article className="offer" key={o.id}><div className="flex"><h2>{o.quantity} × {o.title}</h2><span className="amount">{money(o.price)}</span></div><p>{o.wish||'Richiesta pranzo'}</p><p>Ritiro entro {time(o.pickup_by)} · {o.status==='collected'?'Ritirato':expired?'Scaduta':o.status==='accepted'?'Scelta dal cliente: prepara il ritiro':o.status==='cancelled'?'Non scelta / annullata':'Il cliente sta scegliendo'}</p>{o.status==='accepted'&&!expired&&<form className="actions" onSubmit={e=>{e.preventDefault();run('collect',{offerId:o.id,code:codes[o.id]||''})}}><label>Codice mostrato dal cliente<input required value={codes[o.id]||''} onChange={e=>setCodes({...codes,[o.id]:e.target.value.toUpperCase()})} maxLength={6} placeholder="ABC234" autoComplete="off"/></label><button className="primary" disabled={busy}><PackageCheck size={18}/> Conferma ritiro</button></form>}{o.status==='offered'&&!expired&&<button className="secondary" disabled={busy} onClick={()=>run('withdraw',{offerId:o.id})}>Ritira proposta</button>}{o.status==='collected'&&(o.tx_hash?<a className="link" target="_blank" rel="noreferrer" href={'https://build.avax.network/explorer/fuji/c-chain/tx/'+o.tx_hash}>Transazione Fuji: controlla esito <ExternalLink size={14} style={{display:'inline'}}/></a>:<div className="actions"><button className="secondary" disabled={busy} onClick={()=>chain(o)}>Registra impronta su Fuji</button><span className="caption">Firma del portafoglio di prova Food Arena · nessun costo per il cliente</span></div>)}</article>})}</div>}
 {tab==='menu'&&<><div className="flex"><h2>I piatti che puoi offrire oggi</h2><button className="primary" onClick={()=>setForm(!form)}><Plus size={18}/> Aggiungi piatto</button></div><p className="help">Indica prezzo totale per una porzione, confezione compresa. Riserva queste quantità a Food Arena e tienile separate dagli altri canali. Le quantità vengono riservate quando invii un’offerta. Scadute e non scelte tornano disponibili. Dopo 24 ore serve una nuova disponibilità.</p>{form&&<form className="request-card top-margin" onSubmit={addMeal}><label>Nome piatto / combinazione<input required maxLength={100} value={meal.name} onChange={e=>setMeal({...meal,name:e.target.value})}/></label><label>Ingredienti, porzione, bevanda ed extra inclusi<textarea value={meal.description} onChange={e=>setMeal({...meal,description:e.target.value})} maxLength={350} placeholder="Descrivi esattamente cosa è compreso. Conferma gli allergeni direttamente col cliente."/></label><div className="form-grid"><label>Prezzo totale a porzione (€)<input required type="number" min="1" max="100" step="0.01" value={meal.price} onChange={e=>setMeal({...meal,price:e.target.value})}/></label><label>Porzioni riservate a Food Arena<input required type="number" min="1" max="100" value={meal.stock} onChange={e=>setMeal({...meal,stock:Number(e.target.value)})}/></label><label>Preparazione (minuti)<input required type="number" min="1" max="90" value={meal.prep} onChange={e=>setMeal({...meal,prep:Number(e.target.value)})}/></label><label className="checkline"><input type="checkbox" checked={meal.vegetarian} onChange={e=>setMeal({...meal,vegetarian:e.target.checked})}/> Vegetariano, dichiarato dal locale</label></div><button className="primary" disabled={busy}>Pubblica disponibilità</button></form>}<div className="stack top-margin">{data.menu.map((m:Row)=><article className="offer flex" key={m.id}><div><h3>{m.name}</h3><p>{money(m.price)} · {m.available} disponibili su {m.stock} · {m.prep} min</p><small>{m.description}</small><small>Aggiornato alle {time(m.updated)}</small></div><button className="secondary" disabled={busy} onClick={()=>run('pauseMenu',{id:m.id})}>Sospendi</button></article>)}</div></>}
 <p className="caption top-margin">Accesso: {data.user} · <a className="link" href="/signout-with-chatgpt?return_to=/">Esci</a></p></>}</main></Frame>
}
