'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowUpRight,Check,Clock3,MapPin,Copy,Phone,Sparkles,Utensils,Leaf,Flame} from 'lucide-react';
import {Frame} from '../../customer';
import {api,read,money,time} from '../../shared';
export default function Ticket({id}:{id:string}){
 const [d,setD]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[copied,setCopied]=useState(false),[now,setNow]=useState(Date.now()),[proof,setProof]=useState(''),[ai,setAi]=useState(''),[aiBusy,setAiBusy]=useState(false),[rank,setRank]=useState<string[]>([]);
 const worker=useRef<Worker|null>(null);
 async function refresh(){try{setD(await read('view=request&id='+encodeURIComponent(id)))}catch(e:any){setError(e.message)}}
 useEffect(()=>{refresh();const timer=setInterval(refresh,5000),clock=setInterval(()=>setNow(Date.now()),1000);return()=>{clearInterval(timer);clearInterval(clock);worker.current?.terminate()}},[id]);
 async function act(action:string,offerId?:string,code?:string){setBusy(true);setError('');try{const result=await api(action,{requestId:id,offerId,code});if(action==='demoAttest')setProof(result.confirmed?'Confermata su Avalanche Fuji.':'Transazione inviata. Verifica la conferma tra pochi secondi.');await refresh()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function share(){try{await navigator.clipboard.writeText(location.href);setCopied(true)}catch{setError('Copia il link dalla barra del browser.')}}
 function compare(){setAiBusy(true);setAi('Carico il modello AI nel browser. Il primo avvio può richiedere circa un minuto.');if(!worker.current){worker.current=new Worker('/lunch-ranker.worker.js',{type:'module'});worker.current.onmessage=({data:m})=>{if(m.type==='result'){setRank(m.order);setAi('AI pronta: proposte ordinate per affinità con la richiesta. La scelta resta tua.');setAiBusy(false)}else if(m.type==='error'){setAi('AI non disponibile: puoi confrontare e scegliere le offerte direttamente.');setAiBusy(false)}};worker.current.onerror=()=>{setAi('Modello non caricato. Le offerte restano utilizzabili.');setAiBusy(false)}}worker.current.postMessage({id:crypto.randomUUID(),query:r.wish||'Un pranzo completo e gustoso con acqua',items:offers.map((o:any)=>({id:o.id,name:o.title,description:o.description}))})}
 const r=d?.request,chosen=d?.offers.find((o:any)=>o.id===r?.chosen),expired=r&&r.pickup_by<=now&&r.status!=='collected';
 const offers=(d?.offers.filter((o:any)=>o.status==='offered'&&o.expires>now)||[]).sort((a:any,b:any)=>rank.length?(rank.indexOf(a.id)<0?999:rank.indexOf(a.id))-(rank.indexOf(b.id)<0?999:rank.indexOf(b.id)):a.price-b.price);
 return <Frame><main className="arena-page"><a className="text-link" href="/"><ArrowLeft size={15}/> Torna all’arena</a>{error&&<div className="error" role="alert">{error}</div>}{!d?<p className="loading">Carico la richiesta…</p>:<>
 {r.demo===1&&<div className="demo-banner"><span className="demo-dot"/> ARENA DEMO <span>Locali e pasti fittizi. Puoi provare tutto il percorso.</span></div>}
 <div className="arena-heading"><div><span className="eyebrow">IL TUO BUDGET. LE LORO PROPOSTE.</span><h1>{chosen?'Hai scelto.':offers.length?'Il pranzo si fa avanti.':'La tua arena è aperta.'}</h1><div className="request-meta"><span><MapPin size={15}/> {r.zone}</span><span><Clock3 size={15}/> Entro {time(r.pickup_by)}</span><span>{r.quantity} {r.quantity===1?'persona':'persone'}{r.vegetarian===1?' · vegetariano':''}</span></div>{r.wish&&<p className="help">«{r.wish}»</p>}</div><div className="budget-stamp"><span>BUDGET TOTALE</span><strong>{money(r.budget)}</strong><small>Confezione inclusa</small></div></div>
 <div className="journey"><span className="done"><Check size={14}/> Budget lanciato</span><span className={chosen?'done':'current'}>02 · Scegli il pranzo</span><span className={r.status==='collected'?'done':r.status==='accepted'?'current':''}>03 · {r.demo?'Prova il ritiro':'Ritira al banco'}</span></div>
 {!d.mine&&<div className="notice"><p>Richiesta condivisa: solo chi l’ha creata può scegliere. <a className="link" href="/gestore">Sei un gestore? Rispondi dal tuo pannello.</a></p></div>}
 {chosen?<section className="selected-offer"><div className="selected-main"><span className="eyebrow"><Check size={16}/> {r.demo?'LA TUA SCELTA DEMO':'OFFERTA CONFERMATA'}</span><h2>{chosen.title}</h2><p>{chosen.description}</p><div className="flex top-margin"><strong>{chosen.venue_name}</strong><span className="amount">{money(chosen.price)}</span></div><p className="caption">{chosen.quantity} {chosen.quantity===1?'porzione':'porzioni'} · prezzo totale, confezione compresa.{!r.demo&&' Pagamento al locale.'}</p><div className="notice"><MapPin size={20}/><p>{chosen.address}<br/>Pronto dalle {time(chosen.ready_at)}. Termine: {time(r.pickup_by)}.</p></div><div className="actions">{chosen.phone&&<a className="secondary" href={'tel:'+chosen.phone}><Phone size={16}/> Chiama il locale</a>}{!r.demo&&<a className="secondary" target="_blank" rel="noreferrer" href={'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(chosen.address+' Pescara')}>Apri indirizzo <ArrowUpRight size={16}/></a>}</div></div><div className="pickup-panel">
 {r.status==='accepted'&&!expired&&d.mine&&<><span className="eyebrow">{r.demo?'IL TUO CODICE DEMO':'MOSTRA QUESTO CODICE AL BANCO'}</span><div className="ticket">{chosen.code}</div><p>Una scelta. Un codice. Un solo ritiro.</p>{r.demo===1&&chosen.scripted===1?<><button className="primary wide top-margin" disabled={busy} onClick={()=>act('demoCollect',chosen.id,chosen.code)}>{busy?'Registrazione…':'Simula il ritiro'}<Check size={18}/></button><p className="caption top-margin">Nella prova puoi fare anche la parte del gestore. Nessun ordine reale.</p></>:<p className="caption top-margin">Tieni aperta questa pagina. Il gestore inserirà il codice alla consegna.</p>}</>}
 {r.status==='collected'&&<><span className="completion-mark"><Check size={36}/></span><h2>{r.demo?'Prova completata.':'Buon pranzo!'}</h2><p className="top-margin">{r.demo?'Hai lanciato il budget, scelto un’offerta e registrato il ritiro.':'Il gestore ha registrato il ritiro.'}</p>{r.demo===1&&chosen.scripted===1&&d.mine&&<><button className="secondary wide top-margin" disabled={busy||proof==='Confermata su Avalanche Fuji.'} onClick={()=>act('demoAttest',chosen.id)}>{busy?'Invio alla rete…':chosen.tx_hash?'Verifica conferma su Fuji':'Registra prova su Avalanche'}<ArrowUpRight size={16}/></button><p className="caption top-margin">Registrazione vera sulla rete di prova Fuji. Gratuita per te, senza wallet. Non certifica un pasto reale.</p>{proof&&<p className="success top-margin" role="status">{proof}</p>}</>}</>}
 {expired&&r.status!=='collected'&&<p className="error">Il termine di ritiro è passato.{!r.demo&&' Contatta il locale.'}</p>}
 {chosen.tx_hash&&<p className="caption top-margin"><a className="link" target="_blank" rel="noreferrer" href={'https://subnets-test.avax.network/c-chain/tx/'+chosen.tx_hash}>Apri la transazione su Avalanche Fuji ↗</a></p>}<a className="text-link top-margin" href="/">Lancia un altro budget <ArrowUpRight size={15}/></a></div></section>
 :r.status==='open'&&!expired?<><div className="offers-heading"><h2>{offers.length?`${offers.length} ${offers.length===1?'proposta per te':'proposte per te'}`:'In attesa di proposte'}</h2>{offers.length>1&&<button className="secondary ai-compare" disabled={aiBusy||busy} onClick={compare}><Sparkles size={16}/>{aiBusy?'L’AI sta confrontando…':'Confronta con l’AI'}</button>}</div>{ai&&<p className="model-progress" role="status">{ai}</p>}{!offers.length?<div className="empty"><h3>{r.demo?'Nessuna proposta demo compatibile.':'La richiesta è pubblicata.'}</h3><p>{r.demo?'Prova con 10 € per una persona e 30 minuti. Nella demo ci sono tre menù: anche qui budget, porzioni e tempi devono tornare.':'I gestori della zona possono rispondere dal loro pannello. Riceverai proposte solo quando un locale aderente risponde.'}</p>{!r.demo&&<button className="secondary top-margin" onClick={share}><Copy size={16}/>{copied?'Link copiato':'Copia link della richiesta'}</button>}</div>:<div className="offer-grid">{offers.map((o:any,i:number)=><article className={'offer arena-offer tone-'+i%3} key={o.id}><div className="offer-top"><span className="venue-symbol">{o.title.includes('Focaccia')?<Flame size={28}/>:o.title.includes('Cous')?<Leaf size={28}/>:<Utensils size={28}/>}</span><span className="offer-number">0{i+1}</span></div><div className="offer-body"><div className="flex"><span className="eyebrow">{o.venue_name}</span>{rank[0]===o.id&&<span className="badge"><Sparkles size={12}/> Affinità AI</span>}</div><h2>{o.title}</h2><p>{o.description}</p><div className="offer-price"><strong>{money(o.price)}</strong><span>totale · {o.quantity} {o.quantity===1?'persona':'persone'}<br/>confezione inclusa</span></div><div className="offer-ready"><Clock3 size={17}/><span>Pronto dalle <strong>{time(o.ready_at)}</strong></span></div><small>{o.scripted?'Locale fittizio · nessun ritiro reale':o.address}</small><button className="primary wide" disabled={busy||!d.mine} onClick={()=>act('accept',o.id)}>Scelgo questo <ArrowUpRight size={18}/></button><div className="expiry"><span/> Riservata per {Math.floor(Math.max(0,o.expires-now)/60000)}:{String(Math.floor(Math.max(0,o.expires-now)/1000)%60).padStart(2,'0')}</div></div></article>)}</div>}{d.mine&&<button className="text-button top-margin" disabled={busy} onClick={()=>act('cancel')}>Chiudi questa richiesta</button>}</>:<div className="empty"><h3>{expired?'Il tempo della richiesta è terminato.':'Richiesta annullata.'}</h3><a className="primary top-margin" href="/">Lancia un nuovo budget <ArrowUpRight size={18}/></a></div>}
 </>}</main></Frame>
}
